"""跨资源权限能力。"""

from yuxi.permissions.resource_permission import (
    AGENT_PERMISSION_POLICY,
    ALL_KNOWLEDGE_BASE_CAPABILITIES,
    DEFAULT_KNOWLEDGE_BASE_CAPABILITY_POLICY,
    KNOWLEDGE_BASE_PERMISSION_POLICY,
    SKILL_PERMISSION_POLICY,
    KnowledgeBaseCapability,
    ResourcePermission,
    ResourcePermissionDenied,
    knowledge_base_owner_department_id,
    normalize_knowledge_base_capability_policy,
    normalize_permission_config,
    require_knowledge_base_capability,
    require_knowledge_base_permission,
    require_resource_permission,
    resolve_agent_permission,
    resolve_knowledge_base_capabilities,
    resolve_knowledge_base_permission,
    resolve_resource_permission,
    resolve_skill_permission,
    scope_matches,
)

__all__ = [
    "AGENT_PERMISSION_POLICY",
    "ALL_KNOWLEDGE_BASE_CAPABILITIES",
    "DEFAULT_KNOWLEDGE_BASE_CAPABILITY_POLICY",
    "KNOWLEDGE_BASE_PERMISSION_POLICY",
    "SKILL_PERMISSION_POLICY",
    "KnowledgeBaseCapability",
    "ResourcePermission",
    "ResourcePermissionDenied",
    "knowledge_base_owner_department_id",
    "normalize_knowledge_base_capability_policy",
    "normalize_permission_config",
    "require_knowledge_base_capability",
    "require_knowledge_base_permission",
    "require_resource_permission",
    "resolve_agent_permission",
    "resolve_knowledge_base_capabilities",
    "resolve_knowledge_base_permission",
    "resolve_resource_permission",
    "resolve_skill_permission",
    "scope_matches",
]
